name:                Game
version:             0.1.0.0
github:              "probeiuscorp/haskell-game"
license:             MIT
author:              "Caleb Stimpson"
maintainer:          "caleb.stimpson@gmail.com"
copyright:           "2024 Caleb Stimpson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/probeiuscorp/haskell-game#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- sdl2
- sdl2-ttf
- reactive-banana
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - LambdaCase
  - MultiWayIf
  - TupleSections
  - ScopedTypeVariables
  - RecursiveDo

library:
  source-dirs: src

executables:
  Game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Game

tests:
  Game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Game
